### ISSUE TITLE
Branch "gh-pages" has build errors on ci/circleci

### ISSUE THREAD

**Issue by gmacario** [gmacario/gmacario.github.io#101]
Example:

![Schermata 2021-05-22 alle 22 30 02](https://user-images.githubusercontent.com/75182/119240002-5356b780-bb4d-11eb-92e3-8429cf859254.png)

**Comment by gmacario** [comment]
Expanding details of the failing check https://app.circleci.com/pipelines/github/gmacario/gmacario.github.io/72/workflows/cef0be4c-290a-48d0-8083-fccbcad34d61/jobs/358

![Schermata 2021-05-22 alle 22 33 19](https://user-images.githubusercontent.com/75182/119240064-c06a4d00-bb4d-11eb-9a55-5a54ae8afa21.png)

**Comment by gmacario** [comment]
@GGn0 looking forward another free :coffee: ?

**Comment by gmacario** [comment]
Unfortunately the merged PR #102 did not address the root cause of issue #101

https://app.circleci.com/pipelines/github/gmacario/gmacario.github.io/75/workflows/92fd0da9-eac9-4b5c-903a-0e2dce364d80/jobs/362

**Comment by gmacario** [comment]
@GGn0 ☕ awarded because of #102 and (above all) #103 😂

**Comment by GGn0** [comment]
That's great news!
🎉🎉
