### ISSUE TITLE
Broken link: /images/easybuild-torinotech-2016-04-01.pdf

### ISSUE THREAD

**Issue by gmacario** [gmacario/gmacario.github.io#112]
The link "a presentation about easy-jenkins" on <https://github.com/gmacario/easy-jenkins>

which redirects to
<http://gmacario.github.io/images/easybuild-torinotech-2016-04-01.pdf>

returns "404 - This page could not be found."

The link used to work before the update to Next.js framework.

**Comment by gmacario** [comment]
Notice that the file is still present in the source tree
https://github.com/gmacario/gmacario.github.io/tree/main/images

@GGn0 do you have any ideas where I should look at?

**Comment by GGn0** [comment]
Check out https://github.com/gmacario/gmacario.github.io/pull/109#issuecomment-860060005  
After you merge it you should be able to access the files in the `images` directory

**Comment by gmacario** [comment]
PR #113 has also fixed this bug.

Closing
